# Generated by Django 4.2.9 on 2024-05-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userAccount', '0002_researcher_alter_patient_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Covid', 'COVID'), ('Normal', 'Normal'), ('Pneumonia', 'Pneumonia')], max_length=20)),
                ('patient_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('approved', models.BooleanField(default=False)),
                ('image', models.ImageField(max_length=255, upload_to='report_images/')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_by_id', to='userAccount.patient')),
            ],
        ),
    ]
