# Generated by Django 5.0.3 on 2024-03-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userAccount", "0002_doctor_patient_systemadmin"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="role",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
